# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PositionalAccuracy
                                 A QGIS plugin
 This plugin calculates the mean square error (RMSE), in meters, between the coordinate values present in the spatial data set and its counterpart considered as true. This planimetric error is measured manually and must be represented in a linear feature.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-27
        copyright            : (C) 2020 by Alex Santos
        email                : alxcart@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PositionalAccuracy class from file PositionalAccuracy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .data_quality import PositionalAccuracy
    return PositionalAccuracy(iface)
